# Generated by Django 4.2.7 on 2023-12-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Clase',
        ),
    ]
